\documentclass{article}
\usepackage[utf8]{inputenc}
\usepackage[english]{babel}
\usepackage{dcolumn}
\usepackage{tikz}
\usepackage{amsmath}
\usepackage{amsfonts}

\begin{document}
You can type R commands in your \LaTeX{} document and they will be properly run and the output printed in the document.

<<echo=FALSE, cache=FALSE>>=
library(knitr)
read_chunk("C:\\Users\\marek\\Desktop\\biostatistika\\test\\test.R")
@

<<test>>=
@  
\end{document}